[package]
name = "caesar-build"
version = "1.0.0"
edition = "2021"
authors = ["tomat"]
description = "builder for caesar"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caesar-util = { path = "../caesar-util" }
dialoguer = "0.11.0"
